data_generation:
  type: with_actors # [pure, with_actors]
  seed: 1
  debug: false

  network:
    num_users: 4
    num_steps: 3000

  adversary:
    gamma: 0.01

  controller:
    control_gain: 0.1
    type: adversarial # [random, adversarial, zero]
    kalman_filter:
      process_noise_var: 0.0001    # Q matrix variance
      measurement_noise_var: 0.1  # R matrix variance