data_generation:
  type: only_bad # [pure, with_actors, only_bad]
  seed: 1
  debug: false

  network:
    num_users: 4
    num_steps: 3000

  adversary:
    gamma: 0.2

  controller:
    control_gain: 0.1
    type: random # [random, adversarial]
    kalman_filter:
      process_noise_var: 0.0001    # Q matrix variance
      measurement_noise_var: 0.1  # R matrix variance