data_generation:
  type: with_actors # [pure, with_actors, only_bad]
  seed: 1
  debug: false
  T_pure: 200
  T_only_bad: 500

  network:
    num_users: 4
    num_steps: 1500

  adversary:
    gamma: 0.0

  controller:
    control_gain: 0.1
    type: adversarial # [random, adversarial]
    kalman_filter:
      process_noise_var: 0.0001    # Q matrix variance
      measurement_noise_var: 0.1  # R matrix variance
      trigger_period: 5 # T trigger period
      num_steps_between_random: 5000 # tau excitation period


### Commented out for testing the trigger period parameter
#experiment_name: atic_sweep
#
#hydra:
#  mode: MULTIRUN
#  sweep:
#    dir: multirun/${experiment_name}/${data_generation.seed}_${data_generation.type}
#  run:
#    dir: .
#  sweeper:
#    params:
#      data_generation.type: pure,with_actors,only_bad
#      data_generation.seed: "range(1, 101, 1)" 
